version: "3"

services:
  treedfolio:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    external_links:
      - "host.docker.internal"
